# -*- coding: utf-8 -*-
"""ecg_inference.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tXwoZrSS7oYJ8XpsCMRnoMrFH_YpuwHn
"""

import numpy as np
from tensorflow.keras.models import load_model

# Function for model inference
def predict_ecg_segment(ecg_segment, model_path='models/cnn_base.h5'):
    """
    Takes a single ECG segment and returns the predicted class
    """
    model = load_model(model_path)   # load the trained model

    ecg_segment = ecg_segment[np.where(ecg_segment != 0)[0]]   # Remove padding
    ecg_segment = np.array(ecg_segment).reshape(1, -1, 1)   # reshape

    # prediction
    y_pred_prob = model.predict(ecg_segment)
    y_pred_class = np.argmax(y_pred_prob, axis=1)[0]   # multi-class classification

    class_mapping = {0: 'N', 1: 'S', 2: 'V', 3: 'F', 4: 'Q'}

    return class_mapping[y_pred_class]